// GENERATED by scripts/build_scenes.py — do not edit by hand.
// Run `npm run assets` after changing the artwork or scripts/scenes.json.

export type SceneAsset = {
  name: string;
  bg: string;
  mask: string;
  w: number;
  h: number;
  /** Relative share of the page's scroll length. */
  weight: number;
  /** Present only where a figure was lifted out to be animated. */
  deer?: { x: number; y: number; w: number; h: number };
  deerSrc?: string;
};

export const SCENES: SceneAsset[] = [
  { name: "valley", bg: "/scenes/valley-bg.webp", mask: "/scenes/valley-mask.webp", w: 2944, h: 1648, weight: 1.15, deer: {"x": 735, "y": 1465, "w": 100, "h": 95}, deerSrc: "/scenes/valley-deer.png" },
  { name: "climb", bg: "/scenes/climb-bg.webp", mask: "/scenes/climb-mask.webp", w: 2912, h: 1434, weight: 1.0 },
  { name: "summit", bg: "/scenes/summit-bg.webp", mask: "/scenes/summit-mask.webp", w: 2960, h: 1648, weight: 1.0 },
  { name: "ocean", bg: "/scenes/ocean-bg.webp", mask: "/scenes/ocean-mask.webp", w: 1456, h: 816, weight: 1.0 },
];
